config/routes.rb
Rails.application.routes.draw do
  root to: "image#index"
  resources :image,     only: [:index, :new, :create, :destroy]
  resources :container, only: [:index, :new, :create, :destroy]
  get "/container/start/:id", to: "container#start"
  get "/container/stop/:id", to: "container#stop"
  get "/image/search", to: "image#search"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/container_controller.rb
class ContainerController < ApplicationController
  before_action :set_container, except: [:new]
  def index
    @containers = @container.list(all: true).json
    @containers.map { | c | c["Name"] = c["Names"][0].gsub("/", "") }
  end

  def new
    image = Docker::API::Image.new
    response = image.list
    @images = response.json.map{ | r | r["RepoTags"][0] }
  end

  def create
    host_config = eval(container_params[:host_config])
    response = @container.create( {name: container_params[:name]}, {Image: container_params[:image], HostConfig: host_config })
    if response.success?
      redirect_to container_index_path
    else
      redirect_to new_container_path
    end
  end

  def start
    @container.start(params[:id])
    redirect_to container_index_path
  end

  def stop
    @container.stop(params[:id])
    redirect_to container_index_path
  end

  def destroy
    @container.remove(params[:id])
    redirect_to container_index_path
  end

  def chart
    @containers = @container.list(all: true).json
  end

  private
    def set_container
      @container = Docker::API::Container.new
    end

    def container_params
      params.permit(:name, :image, :host_config)
    end
end

app/controllers/image_controller.rb
class ImageController < ApplicationController
  before_action :set_image
  def index
    @images = @image.list.json
  end

  def new
  end

  def create
    response = @image.create( fromImage: "#{image_params[:repo]}:#{image_params[:tag]}" )
    if response.success?
      redirect_to image_index_path
    else
      render :new
    end
  end

  def destroy
    @image.remove(params[:id])
    redirect_to image_index_path
  end

  def search
    @image = @image.search('term' => image_params[:search])
    @images = @image.json
  end

  private

    def set_image
      @image = Docker::API::Image.new
    end

    def image_params
      params.permit(:repo, :tag, :search)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/container_helper.rb
module ContainerHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/image_helper.rb
module ImageHelper
end

app/views/container/index.html.erb
<h1 class="text-center mt-4"> Listing All Containers </h1>
<div class="container">
  <div class="row justify-content-md-center">
      <table class="table caption-top ">
        <caption>List of Containers</caption>
        <thead class="table-dark">
          <th>Name</th>
          <th>Image</th>
          <th>State</th>
          <th colspan="3"></th>
         </thead>
        <tbody>
          <% @containers.each do |container| %>
            <tr>
              <td><%= container["Name"] %></td>
              <td><%= container["Image"] %></td>
              <td><%= container["State"] %></td>
              <td><%= link_to 'Start', "/container/start/#{container['Id']}", class: "btn btn-outline-success" %></td>
              <td><%= link_to 'Stop', "/container/stop/#{container['Id']}",  class: "btn btn-outline-secondary"  %></td>
              <td><%= link_to 'Delete', container_path(container["Name"]), method: :delete, data: { confirm: 'Are you sure?' },  class: "btn btn-outline-danger" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
  </div>
</div>

app/views/container/new.html.erb
<h1 class="text-center mt-4"> New Container </h1>
<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-10">
            <%= form_with(url: "/container", method: "post", class: "shadow p-3 mb-3 bg-dark rounded", local: true) do |f| %>
                <div class="input-group row mb-3">
                    <%= f.label :Name, class: "col-2 col-form-label text-white"%>
                    <div class="col-10">
                        <%= f.text_field :repo, class: "form-control shadow rounded", placeholder: "Name of container" %>
                    </div>
                </div>

                <div class="input-group row mb-3">
                    <%= f.label :Image, class: "col-2 col-form-label text-white"%>
                    <div class="col-10">
                         <%= f.select :image, options_for_select(@images, @images.first), {}, {class: "form-control shadow rounded"} %>
                    </div>
                </div>

                <div class="input-group row mb-3">
                    <%= f.label :Configurations, class: "col-2 col-form-label text-white"%>
                    <div class="col-10">
                        <%= f.text_area :host_config, class: "form-control shadow rounded", placeholder: "{PortBindings: {“80/tcp”: [ {HostIp: “0.0.0.0”, HostPort: “80”} ]}}" %>
                    </div>
                </div>

                <div class="input-group justify-content-center">
                    <%= f.submit "Create", class: "btn btn-outline-success btn-lg" %>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/image/index.html.erb
<h1 class="text-center mt-4"> Listing All Images </h1>
<div class="container">
  <div class="row justify-content-md-center">
    <table class="table caption-top ">
      <caption>List of Docker Images</caption>
      <thead class="table-dark">
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Size</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <% @images.each do |image| %>
          <tr>
            <td><%= image["RepoTags"][0] %></td>
            <td><%= number_to_human_size(image["Size"].to_f) %></td>

            <td><%= link_to 'Delete', image_path(image["Id"]), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/image/new.html.erb
<h1 class="text-center mt-4"> Pull Image </h1>
<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-10">
            <%= form_with(url: "/image", method: "post", class: "shadow p-3 mb-3 bg-dark rounded", local: true) do |f| %>
                <div class="input-group row mb-3">
                    <%= f.label :Name, class: "col-2 col-form-label text-white"%>
                    <div class="col-10">
                        <%= f.text_field :repo, class: "form-control shadow rounded", placeholder: "Name of docker image" %>
                    </div>
                </div>

                <div class="input-group row mb-3">
                    <%= f.label :Tag, class: "col-2 col-form-label text-white"%>
                    <div class="col-10">
                        <%= f.text_field :tag, class: "form-control shadow rounded", placeholder: "Tag of docker image" %>
                    </div>
                </div>

                <div class="input-group justify-content-center">
                    <%= f.submit "Pull", class: "btn btn-outline-success btn-lg" %>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/image/search.html.erb
<h1 class="text-center mt-4"> Search for Images </h1>
<div class="container">
  <div class="row justify-content-md-center">

    <div class="col-10">
            <%= form_with(url: image_search_path, method: "get", class: "shadow p-3 mb-3 bg-dark rounded", local: true) do |f| %>
                <div class="input-group row mb-3">
                    <%= f.label :Name, class: "col-2 col-form-label text-white"%>
                    <div class="col-10">
                        <%= f.text_field :search, class: "form-control shadow rounded", placeholder: "Name of the image" %>
                    </div>
                </div>

                <div class="input-group justify-content-center">
                    <%= f.submit "Search", class: "btn btn-outline-success btn-lg" %>
                </div>
            <% end %>
        </div>

    <% if @images.any? %>

        <table class="table caption-top ">
          <caption>List of Images Found</caption>
          <thead class="table-dark">
            <tr>
              <th scope="col">Name</th>
              <th scope="col">Description</th>
              <th scope="col">Stars</th>
            </tr>
          </thead>
          <tbody>
            <% @images.each do |image| %>
              <tr>
                <td><%= image["name"] %></td>
                <td><%= image["description"] %></td>
                <td><%= image["star_count"] %></td>
              </tr>
            <% end %>
          </tbody>
        </table>

    <% end %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="flex-shrink-0 py-4 bg-dark text-white">
    <div class="container text-center">
        <small>Copyright &copy; <%= link_to "Mauricio Magnani", "http://cognition.sh", class: "text-white" %></small>
    </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <%= link_to "Eridanus", root_path, class: "navbar-brand", id: "logo" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                 <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <%= link_to "Images", image_index_path, class: "nav-link active" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Pull image", new_image_path, class: "nav-link active" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Search image", image_search_path, class: "nav-link active" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Containers", container_index_path, class: "nav-link active" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "New Container", new_container_path, class: "nav-link active" %>
                    </li>
                </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>